Policies test update
marmotitude/s3-specs pull request #23
Opened 2024-11-28 17:10 UTC by 2xlhe

2024-11-28 19:14 UTC, fczuardi requested changes

2024-11-28 19:14 UTC, fczuardi commented on docs/policies_test.py
> +def test_setup_policies(s3_client, existing_bucket_name, actions, effect = 'Allow'):
o arg effect está estranho, já que nao é alterado pelo parametrize

2024-11-28 19:14 UTC, fczuardi commented on docs/policies_test.py
> +        assert e.response['Error']['Code'] == 'BucketNotExists'
estranho

2024-11-28 19:14 UTC, fczuardi commented on docs/policies_test.py
> +        s3_client.head_bucket(Bucket = bucket_name)
este teste testa o head bucket nos 3 casos, ficou confuso o parametrize ter 3 actions com deny e o teste nao testar estas actions

2024-11-28 19:27 UTC, 2xlhe commented on docs/policies_test.py
> +def test_setup_policies(s3_client, existing_bucket_name, actions, effect = 'Allow'):
este caso eh para testes futuros para onde ele varie

2024-12-02 21:07 UTC, fczuardi requested changes

2024-12-02 21:07 UTC, fczuardi commented on docs/profiles_policies_test.py
> +    return multiple_s3_clients[0]
```suggestion
```

2024-12-04 19:24 UTC, fczuardi requested changes

2024-12-05 13:38 UTC, 2xlhe commented on docs/profiles_policies_test.py
> +tenant = {TENANT-ID}
eh um auxilio e eh utilizado nos testes

2024-12-05 13:43 UTC, fczuardi requested changes

2024-12-05 13:43 UTC, fczuardi commented on docs/conftest.py
> +    :param request: dictionary of policy related arguments
vai ficar para um followup

2024-12-05 14:20 UTC, fczuardi requested changes

2024-12-05 14:20 UTC, fczuardi commented on docs/policies_test.py
> +    assert method(**kwargs)
melhora este assert aqui para testar o que é uma response de sucesso mesmo, talvez olhar o http status code pelo menos

2024-12-05 14:20 UTC, fczuardi commented on docs/profiles_policies_test.py
> +    assert method(**kwargs)
mesmo caso de cima

2024-12-05 14:36 UTC, fczuardi commented on docs/profiles_policies_test.py
> +tenant = {TENANT-ID}
vamos usar aquele truque de list-buckets para obter o tenant-id de quem precisar, dado um profile

2024-12-05 18:07 UTC, 2xlhe commented on docs/policies_test.py
> +    assert s3_client.put_bucket_policy(Bucket=bucket_name, Policy=policies)
o retorno eh 204

2024-12-05 20:54 UTC, fczuardi approved these changes

2024-12-05 20:58 UTC, merged