Create tests for Cold Storage
marmotitude/s3-specs pull request #25
Opened 2024-12-04 13:57 UTC by luizantonio26

2024-12-04 19:04 UTC, matheusvictorello commented on docs/conftest.py
> +    object_key = "large_file.txt"
Não precisa criar arquivo no disco pra upar, o body pode ser bytes:
DATA_5M = b"0" * 1024 * 1024 * 5

2024-12-04 19:05 UTC, matheusvictorello commented on docs/conftest.py
> +def bucket_with_one_object_and_cold_storage_class(s3_client):
content = b"Sample content for testing presigned URLs." é meio confuso nesse contexto de storage class.

2024-12-04 19:05 UTC, matheusvictorello commented on docs/conftest.py
> +def bucket_with_one_object_and_cold_storage_class(s3_client):
Acho que seria melhor algo do tipo como nome: bucket_with_one_storage_class_cold_object

2024-12-04 19:38 UTC, fczuardi requested changes

2024-12-04 19:38 UTC, fczuardi commented on docs/cold_storage_test.py
> +import json
vamos limpar os que nao estao sendo usados

```suggestion
```

2024-12-04 19:38 UTC, fczuardi commented on docs/cold_storage_test.py
> +from datetime import datetime, timedelta, timezone
idem ao comentário acima

```suggestion
from s3_helpers import run_example
```

2024-12-04 19:38 UTC, fczuardi commented on docs/cold_storage_test.py
> +config = "../params/br-ne1.yaml"
como só suportamos no Sudeste 1, seria legal este exemplo vir com uma config que funcione

```suggestion
config = "../params/br-se1.yaml"
```

2024-12-04 19:38 UTC, fczuardi commented on docs/cold_storage_test.py
> +# run_example(__name__, "test_upload_object_with_cold_storage_class", config=config)
pode remover

```suggestion
```

2024-12-04 19:38 UTC, fczuardi commented on docs/cold_storage_test.py
> +    # Teste de upload
```suggestion
    # A biblioteca boto3 somente aceita uma lista específica de nomes de storage class, os nomes que a AWS usa, exemplos "STANDARD", "GLACIER_IR", etc.
    #  Na Magalu Cloud, a classe de armazenamento "Cold Instant" por motivos de compatibilidade aceita também chamadas com o nome da AWS GLACIER_IR.
```

2024-12-04 19:38 UTC, fczuardi commented on docs/cold_storage_test.py
> +    storage_class = storage_class.get("StorageClass")
apenas uma preferencia pessoal minha, sinta-se livre para ignorar esta sugestão e marcar como resolvido, mas eu nao sou muito fã de reatribuir valor a mesma variavel...

```suggestion
    object_attributes = s3_client.get_object_attributes(Bucket=bucket_name, Key=object_key, ObjectAttributes = ["StorageClass"])
    
    storage_class = object_attributes.get("StorageClass")
```

2024-12-04 19:50 UTC, fczuardi requested changes

2024-12-04 19:50 UTC, fczuardi commented on docs/cold_storage_test.py
> +def test_boto_upload_object_with_cold_storage_class(s3_client, empty_bucket_name):
Acho que vale uma célula de markdown aqui em cima explicando o que o teste quer mostrar, que neste caso é "como subir um objeto novo, já com uma classe de armazenamento específica em boto3"

2024-12-04 19:50 UTC, fczuardi commented on docs/cold_storage_test.py
> +def test_boto_change_object_class_to_cold_storage(s3_client, empty_bucket_name):
explique numa celula de markdown que além de subir novos objetos ja com uma classe de armazenamento, é possível trocar a classe de armazenamento de um objeto existente, usando a função copy_object do boto3, copiando um objeto para o mesmo lugar (mesma object key) mas passando um valor diferente para o argumento StorageClass

2024-12-04 19:50 UTC, fczuardi commented on docs/cold_storage_test.py
> +    assert storage_class == "STANDARD", "Expected StorageClass STANDARD"
como este setup não é o que você quer documentar neste exemplo, pode abstrair numa fixture... por sorte já temos uma fixture que faz este setup, acho que o nome é bucket_with_one_object ou algo assim.... procure lá

2024-12-04 20:06 UTC, fczuardi requested changes

2024-12-04 20:06 UTC, fczuardi commented on docs/cold_storage_test.py
> +    assert 'URI' in list(acl.keys()), "Expected acl have URI attribute"
nao sei se é util para mostrar algo este assert aqui de URI

2024-12-04 20:11 UTC, fczuardi commented on docs/cold_storage_test.py
> +def test_boto_multipart_upload_with_cold_storage_class(s3_client, empty_bucket_name, create_big_file_with_two_parts):
nitpick: o nome da fixture poderia ser multipart_object ou algo nesta linha... acho que nao precisa ser "big" um multipart upload

2024-12-04 20:12 UTC, fczuardi commented on docs/cold_storage_test.py
> +    response = s3_client
nao entendi esta linha, está meio estranha

2024-12-04 20:15 UTC, fczuardi commented on docs/cold_storage_test.py
> +        with open(part_file, "rb") as part_content:
acho que esta parte voce ja vai refatorar por conta dos comments do Victorelo

2024-12-04 20:17 UTC, fczuardi commented on docs/cold_storage_test.py
> +            assert i in list_parts_num, "Expected part number be in the list_parts response"
isto seria melhor estar fora do for

2024-12-04 20:27 UTC, fczuardi requested changes

2024-12-04 20:27 UTC, fczuardi commented on docs/conftest.py
> +    delete_bucket_and_wait(s3_client, bucket_name)
adapta a `existing_bucket_name` que ja tem neste arquivo, as duas parecem ter o mesmo propósito

2024-12-04 20:27 UTC, fczuardi commented on docs/conftest.py
> +def bucket_with_one_object_and_cold_storage_class(s3_client):
e se ao inves de subir o object nesta fixture voce reusasse a fixture de bucket with one object e fizesse o copy para trocar a classe? a vantagem seria nao precisar escrever o teardown

se for por este caminho, nao precisa alterar o put object and wait do s3 helper

2024-12-05 21:05 UTC, fczuardi approved these changes

2024-12-05 21:40 UTC, merged